document.write('		<!-- footer -->         ');
document.write('		<footer>            ');
document.write('		    <div class="footer_wrap">           ');
document.write('		        <p>COPYRIGHT KHNP CO.,LTD. ALL RIGHTS RESERVED.</p>         ');
document.write('		    </div>          ');
document.write('		</footer>           ');
document.write('		<!-- //footer -->           ');
document.write('		<span class="sidebar_btn"></span>                          ');
document.write('		<div class="sidebar_wrap">                         ');
document.write('		    <div class="sidebar_tab">                          ');
document.write('		        <input checked="checked" id="a_tab1" type="radio" name="sidebar_tab" />                        ');
document.write('		        <input id="a_tab2" type="radio" name="sidebar_tab" />                          ');
document.write('		        <nav>                          ');
document.write('		          <label class="tab1" for="a_tab1">Notice</label>                          ');
document.write('		          <label class="tab2" for="a_tab2">Skin</label>                        ');
document.write('		          <a class="sidebar_close"></a>                        ');
document.write('		        </nav>                         ');
document.write('		        <section>                          ');
document.write('		            <div class="tab1 tab_content">                         ');
document.write('		                <ul class="notice_list">                           ');
document.write('		                    <li onclick="location.href=&#39;#none&#39;">                           ');
document.write('		                    <span>회원가입 신청시 아이디 형식 알림</span>                          ');
document.write('		                    <span>2023-00-00</span>                        ');
document.write('		                    </li>                          ');
document.write('		                    <li onclick="location.href=&#39;#none&#39;">                           ');
document.write('		                    <span>월성 3,4호기 제어프로랩 해설집 (2014년 개정본) 등록알림</span>                           ');
document.write('		                    <span>2023-00-00</span>                        ');
document.write('		                    </li>                          ');
document.write('		                    <li onclick="location.href=&#39;#none&#39;">                           ');
document.write('		                    <span>[좋은정보] 경보원인 추적 시스템 이용하세요!</span>                           ');
document.write('		                    <span>2023-00-00</span>                        ');
document.write('		                    </li>                          ');
document.write('		                </ul>                          ');
document.write('		            </div>                         ');
document.write('		            <div class="tab2 tab_content">                         ');
document.write('		                <ul class="skin_list">                         ');
document.write('		                    <li class="skin00 active" data-wrapclass="skin00"><span></span></li>                           ');
document.write('		                    <li class="skin01" data-wrapclass="skin01 dark"><span></span></li>                          ');
document.write('		                    <li class="skin02" data-wrapclass="skin02 dark"><span></span></li>                          ');
document.write('		                    <li class="skin03" data-wrapclass="skin03 dark"><span></span></li>                          ');
document.write('		                    <li class="skin04" data-wrapclass="skin04 dark"><span></span></li>                          ');
document.write('		                    <li class="skin05" data-wrapclass="skin05 dark"><span></span></li>                          ');
document.write('		                    <li class="skin06" data-wrapclass="skin06 dark"><span></span></li>                          ');
document.write('		                    <li class="skin07" data-wrapclass="skin07 dark"><span></span></li>                          ');
document.write('		                    <li class="skin08" data-wrapclass="skin08 dark"><span></span></li>                          ');
document.write('		                    <li class="skin09" data-wrapclass="skin09 dark"><span></span></li>                          ');
document.write('		                    <li class="skin10" data-wrapclass="skin10 light"><span></span></li>                           ');
document.write('		                    <li class="skin11" data-wrapclass="skin11 light"><span></span></li>                          ');
document.write('		                    <li class="skin12" data-wrapclass="skin12 light"><span></span></li>                          ');
document.write('		                    <li class="skin13" data-wrapclass="skin13 light"><span></span></li>                          ');
document.write('		                    <li class="skin14" data-wrapclass="skin14 light"><span></span></li>                          ');
document.write('		                    <li class="skin15" data-wrapclass="skin15 light"><span></span></li>                          ');
document.write('		                    <li class="skin16" data-wrapclass="skin16 light"><span></span></li>                          ');
document.write('		                    <li class="skin17" data-wrapclass="skin17 light"><span></span></li>                          ');
document.write('		                    <li class="skin18" data-wrapclass="skin18 light"><span></span></li>                          ');
document.write('		                    <li class="skin19" data-wrapclass="skin19 light"><span></span></li>                          ');
document.write('		                </ul>                          ');
document.write('		            </div>                         ');
document.write('		        </section>                         ');
document.write('		    </div>                         ');
document.write('		</div>                         ');