document.write('  <!-- header_wrap -->          ');
document.write('  <div class="header_wrap">         ');
document.write('      <div class="gnb_wrap_area">            ');
document.write('          <div class="gnb_wrap">            ');
document.write('              <h1 onclick="location.href=&#39;main.html&#39;" title="월성 3,4 호기 원격감시시스템"></h1>            ');
document.write('              <!-- fnc_menu_wrap -->            ');
document.write('              <div class="fnc_menu_wrap">           ');
document.write('                  <a href="#none" target="_blank" class="link_site">EOF</a>         ');
document.write('                  <!-- fnc_menu -->         ');
document.write('                  <div class="fnc_menu">            ');
document.write('                      <ul>          ');
document.write('                          <li class="fnc_notice" onclick="location.href=&#39;공지사항.html&#39;" title="Topic"></li>            ');
document.write('                          <li class="fnc_data" title="Data"></li>           ');
document.write('                          <li class="fnc_sitemap" title="Site Map"></li>            ');
document.write('                          <li class="fnc_help" title="Help"></li>           ');
document.write('                          <li class="fnc_user">         ');
document.write('                              <div class="fnc_user_detail">         ');
document.write('                                  <span>홍길동 님</span>            ');
document.write('                                  <a class="btn_list" href="#none">비밀번호 변경</a>            ');
document.write('                                  <a class="btn_list" href="#none">Log Out</a>          ');
document.write('                                  <a class="btn_list" onclick="openLayer(&#39;modal_login&#39;);">Log In</a>          ');
document.write('                              </div>            ');
document.write('                          </li>         ');
document.write('                      </ul>         ');
document.write('                  </div>            ');
document.write('                  <!-- //fnc_menu -->           ');
document.write('              </div>            ');
document.write('              <!-- //fnc_menu_wrap -->          ');
document.write('          </div>            ');
document.write('      </div>            ');
document.write('      <!-- lnb_menu -->         ');
document.write('      <div class="lnb_wrap_area">            ');
document.write('      <div class="lnb_wrap">            ');
document.write('          <div class="lnb_tab">         ');
document.write('              <a href="DCC_Main.html" class="current">DCC</a>           ');
document.write('              <a href="1-1_LOAD_CONTROL.html" >MARK_V</a>           ');
document.write('          </div>            ');
document.write('          <div class="lnb_menu">            ');
document.write('              <ul>          ');
document.write('                  <li class="current">          ');
document.write('                      <a href="#none">Mimic</a>         ');
document.write('                      <div class="lnb_menu_depth">          ');
document.write('                          <div class="lnb_depth_wrap">          ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">PRIMARY</a>           ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="1-1_LZC_I.html">LZC I</a></li>            ');
document.write('                                          <li><a href="1-2_LZC_II.html">LZC II</a></li>           ');
document.write('                                          <li><a href="1-3_PHT.html">PHT</a></li>          ');
document.write('                                          <li><a href="1-4_PHT_CONTROL.html">PZR CTRL</a></li>         ');
document.write('                                          <li><a href="1-5_MODERATOR.html">MODERATOR</a></li>            ');
document.write('                                          <li><a href="1-6_PHT_PURI.html">PHT PURI</a></li>         ');
document.write('                                          <li><a href="#none">ECC</a></li>          ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">SECONDARY</a>         ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="2-1_MAIN_STEAM.html">MAIN STEAM</a></li>            ');
document.write('                                          <li><a href="2-2_FEED_WATER.html">FEED WATER</a></li>           ');
document.write('                                          <li><a href="2-3_CONDENSATE.html">CONDENSATE</a></li>           ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">FUEL</a>          ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="3-1_F_H_MAIN.html">F/H MAIN</a></li>         ');
document.write('                                          <li><a href="#none">D20 CTRL(A)</a></li>          ');
document.write('                                          <li><a href="#none">D20 CTRL(C)</a></li>          ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">RADIATION</a>         ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="#none">RAD MAIN</a></li>         ');
document.write('                                          <li><a href="#none">RB BASE</a></li>          ');
document.write('                                          <li><a href="#none">RB 1F</a></li>            ');
document.write('                                          <li><a href="#none">RB 2F</a></li>            ');
document.write('                                          <li><a href="#none">RB 3F</a></li>            ');
document.write('                                          <li><a href="#none">RB 4F</a></li>            ');
document.write('                                          <li><a href="#none">RB 5F</a></li>            ');
document.write('                                          <li><a href="#none">SB BASE</a></li>          ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                          </div>            ');
document.write('                      </div>            ');
document.write('                  </li>         ');
document.write('                  <li>          ');
document.write('                      <a href="#none">Trend</a>         ');
document.write('                      <div class="lnb_menu_depth">          ');
document.write('                          <div class="lnb_depth_wrap">          ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">TREND</a>         ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="#none">FIXED</a></li>            ');
document.write('                                          <li><a href="#none">SPARE</a></li>            ');
document.write('                                          <li><a href="#none">FTAM TREND</a></li>           ');
document.write('                                          <li><a href="#none">DCC & Mark-V</a></li>         ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">BARCHART</a>          ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="#none">FIXED</a></li>            ');
document.write('                                          <li><a href="#none">SPARE</a></li>            ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">LOG</a>           ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="3-1_fixed.html">FIXED</a></li>            ');
document.write('                                          <li><a href="3-2_SPARE.html">SPARE</a></li>            ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="4-1_NUMERICAL.html">NUMERICAL</a>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                          </div>            ');
document.write('                      </div>            ');
document.write('                  </li>         ');
document.write('                  <li>          ');
document.write('                      <a href="#none">Alarm</a>         ');
document.write('                      <div class="lnb_menu_depth">          ');
document.write('                          <div class="lnb_depth_wrap">          ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">ALARM</a>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">SUMMARY</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-3_조기경보.html">조기경보</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-4_정주기시험보조자료.html">정주기시험보조자료</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-5_가스크로마토그래프.html">가스크로마토그래프</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">연료프린트</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                          </div>            ');
document.write('                      </div>            ');
document.write('                  </li>         ');
document.write('                  <li>          ');
document.write('                      <a href="#none">Status</a>            ');
document.write('                      <div class="lnb_menu_depth">          ');
document.write('                          <div class="lnb_depth_wrap">          ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">SCHEMATIC</a>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-2_RRS.html">RRS</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-3_HTC.html">HTC</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-4_MTC.html">MTC</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-5_SGP.html">SGP</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-6_SGL.html">SGL</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-7_PHT_PUMP.html">PHT PUMP</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">ZONE VALUES</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">ZONE</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">ZONE COMPARE</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">ADJ ROD</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">REACTIVITY</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-13_STEPBACK_STATUS.html">STEPBACK</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-14_SETBACK_STATUS.html">SETBACK</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">CH TEMP</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                          </div>            ');
document.write('                      </div>            ');
document.write('                  </li>         ');
document.write('                  <li>          ');
document.write('                      <a href="#none">Perfomance</a>            ');
document.write('                      <div class="lnb_menu_depth">          ');
document.write('                          <div class="lnb_depth_wrap">          ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">주요기기 성능감시</a>         ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="1-1_FIXED.html">FIXED</a></li>            ');
document.write('                                          <li><a href="1-2_SHARED.html">SPARE</a></li>            ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="2-1_COMPARE34.html">COMPARE 34</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="2-2_COMPARE_XY.html">COMPARE XY</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="2-3_irrational_AI.html">Inatioal AI</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">SCM</a>           ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="2-5_필수안전변수.html">필수안전변수</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">DCC 관리</a>          ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="3-1_DDC_SELF_CHECK.html">DCC SELF CHECK</a></li>           ');
document.write('                                          <li><a href="3-2_주요계통IO상태.html">중요계통 I/O 상태</a></li>            ');
document.write('                                          <li><a href="#none">DCC Status</a></li>           ');
document.write('                                          <li><a href="3-4_PROGRAM_ON_OFF.html">Programe ON/OFF</a></li>          ');
document.write('                                          <li><a href="3-5_AI_CHECK.html">AI CHECK</a></li>         ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                          </div>            ');
document.write('                      </div>            ');
document.write('                  </li>				            ');
document.write('                  <li>          ');
document.write('                      <a href="#none">Tip</a>           ');
document.write('                      <div class="lnb_menu_depth">          ');
document.write('                          <div class="lnb_depth_wrap">          ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-1_IO_LIST.html">I/O LIST</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">SETPOINT</a>          ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="1-2-1_SDS_1.html">SDS #1</a></li>           ');
document.write('                                          <li><a href="1-2-2_SDS_2.html">SDS #2</a></li>           ');
document.write('                                          <li><a href="1-2-3_SETBACK.html">SETBACK</a></li>          ');
document.write('                                          <li><a href="1-2-4_STEPBACK.html">STEPBACK</a></li>         ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">UNIT CONV</a>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="1-4_원자료출력환산표.html">원자로출력환산표</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                          </div>            ');
document.write('                      </div>            ');
document.write('                  </li>         ');
document.write('                  <li>          ');
document.write('                      <a href="#none">Admin</a>         ');
document.write('                      <div class="lnb_menu_depth">          ');
document.write('                          <div class="lnb_depth_wrap">          ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="사용자관리.html">사용자관리</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="현재접속현황.html">현재접속현황</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="IO_LIST관리.html">I/O LIST 관리</a>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">시스템모니터링</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="시스템개선사항.html">시스템개선사항</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">DCC형상관리</a>           ');
document.write('                                      <ul>          ');
document.write('                                          <li><a href="SW형상관리.html">S/W 형상관리</a></li>         ');
document.write('                                          <li><a href="#none">H/W 형상관리</a></li>         ');
document.write('                                          <li><a href="PCB.html">PCB</a></li>          ');
document.write('                                          <li><a href="재기동관리.html">재기동관리</a></li>           ');
document.write('                                      </ul>         ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">자료실</a>            ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                              <ul>          ');
document.write('                                  <li>          ');
document.write('                                      <a href="#none">EOF 현황</a>          ');
document.write('                                  </li>         ');
document.write('                              </ul>         ');
document.write('                          </div>            ');
document.write('                      </div>            ');
document.write('                  </li>         ');
document.write('              </ul>         ');
document.write('          </div>            ');
document.write('          <div class="lnb_status">          ');
document.write('              <div class="lnb_dp">3X 2022-11-14 10:01:36</div>          ');
document.write('              <div class="toggle_reactor">         ');
document.write('                  <input id="3" name="view_reactor" type="radio" checked>         ');
document.write('                  <label for="3">3</label>         ');
document.write('                  <input id="4" name="view_reactor" type="radio">         ');
document.write('                  <label for="4">4</label>         ');
document.write('                  <span class="button"></span>         ');
document.write('              </div>         ');
document.write('              <div class="toggle_xy">         ');
document.write('                  <input id="X" name="view" type="radio" checked>         ');
document.write('                  <label for="X">X</label>         ');
document.write('                  <input id="Y" name="view" type="radio">         ');
document.write('                  <label for="Y">Y</label>         ');
document.write('                  <span class="button"></span>         ');
document.write('              </div>         ');
document.write('          </div>            ');
document.write('      </div>            ');
document.write('      <!-- //lnb_menu -->           ');
document.write('  </div>            ');
document.write('  </div>            ');
document.write('    <!-- //header_wrap -->           ');
document.write('    <!-- layer_pop_wrap -->           ');
document.write('    <div class="layer_pop_wrap login" id="modal_login">           ');
document.write('        <!-- header_wrap -->           ');
document.write('    	<div class="pop_header">           ');
document.write('    	    <h3>Log In</h3>           ');
document.write('            <a onclick="closeLayer(&#39;modal_login&#39;);" title="Close"></a>           ');
document.write('        </div>           ');
document.write('    	<!-- //header_wrap -->           ');
document.write('    	<!-- pop_contents -->           ');
document.write('    	<div class="pop_contents">           ');
document.write('            <!-- login_wrap -->           ');
document.write('            <div class="login_wrap">           ');
document.write('                <input type="text" name="id" placeholder="아이디">           ');
document.write('                <input type="password" name="password" placeholder="비밀번호">           ');
document.write('                <a href="#none" class="login_btn">로그인</a>           ');
document.write('            </div>           ');
document.write('            <!-- //login_wrap -->           ');
document.write('    	</div>           ');
document.write('    	<!-- pop_contents -->           ');
document.write('    </div>           ');
document.write('    <!-- //layer_pop_wrap -->           ');