spring:
  profiles: local

props:
  domain: http://10.135.101.221:8090
  url: http://10.135.101.221:8090
  

  # attach file dir
  #  attach-path: /Users/JYH/Develop/temp/tdms_file/
  attach-path: C:/temp/tdms_file
