spring:
  profiles: local

datasource:
  mssql-dcc:
    type: org.apache.commons.dbcp2.BasicDataSource
    jdbc-url: jdbc:sqlserver://127.0.0.1:1433;databaseName=DCCDB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: dcc
    password: dcc
    hikari:
    pool-name: mkpenc-pool
    maximum-pool-size: 20
    minimum-idle: 5
  mssql-mark:
    type: org.apache.commons.dbcp2.BasicDataSource
    jdbc-url: jdbc:sqlserver://127.0.0.1:1433;databaseName=MARKDB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: dcc
    password: dcc
    hikari:
    pool-name: mkpenc-pool
    maximum-pool-size: 20
    minimum-idle: 5    
---

spring:
  profiles: dev

datasource:
  mssql:
    type: org.apache.commons.dbcp2.BasicDataSource
    jdbc-url: jdbc:mysql://192.0.1.236:3306/tdms?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: onmakers
    password: dhsapdlzjtm
